name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Pull
        run: |
          git pull
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Display branch name
        run: |
          echo "Branch name is: ${{steps.extract_branch.outputs.branch}}"
          echo $GITHUB_SHA
      - name: Semantic Release runs
        id: semantic-release
        run: DEBUG=semantic-release:* $(npm bin)/semantic-release  -t \${version}