name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs: # inputs in an event which can be accessed by ${{github.events.inputs}}
      name:
        description: "Person to Greet"
        default: "World"
        required: true
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Send Greetings
        run: |
          echo "Hello ${{ github.events.inputs.name }}"