name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Pull and Make install
        run: |
          git pull
          make install
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Display branch name
        run: |
          echo "Branch name is: ${{steps.extract_branch.outputs.branch}}"