name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs: # inputs in an event which can be accessed by ${{github.events.inputs}}
      name:
        description: "Person to Greet"
        default: "World"
        required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo hello
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.step1}} ${{needs.job1.outputs.output2}}