name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch
jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.semantic-release.outputs.TAG_NAME }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Node install
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: |
          npm i
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Display branch name
        run: |
          echo "Branch name is: ${{steps.extract_branch.outputs.branch}}"
          echo $GITHUB_SHA
      - name: Semantic Release runs
        id: semantic-release
        run: DEBUG=semantic-release:* $(npm bin)/semantic-release  -t \${version}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Print tag name
        run: echo ${{ steps.semantic-release.outputs.TAG_NAME }}