name: dotnet-version-check
run-name: ${{ github.actor }} page 2
on:
  workflow_dispatch
jobs:
#  job1:
#    name: Running job1
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: run child process
#        run: |
#          node .github/scripts/test_child_process.js
      
  # job2:
  #   name: Running job2
  #   runs-on: ubuntu-latest
  #   steps:          
  #     - name: Setup .NET Core SDK
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: '7.0.103'
  #     - name: Display
  #       run: ls /usr/share/dotnet/sdk/
  #     - name: Remove faulty SDK version
  #       run: sudo rm -rf /usr/share/dotnet/sdk/{7*,8*}
  #     - name: Display
  #       run: ls /usr/share/dotnet/sdk/
  #     - name: Get installed dotnet version
  #       run: dotnet --version

  job3:
    name: Running job on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Current Directory
        run: pwd
      - name: List Files
        run: dir
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: .github\workflows\global.json
      - name: Display
        run: dotnet --info
      - name: Get installed dotnet version
        run: dotnet --version
