name: page-2
run-name: ${{ github.actor }} page 2
on:
  workflow_dispatch
jobs:
#  job1:
#    name: Running job1
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: run child process
#        run: |
#          node .github/scripts/test_child_process.js
      
  job2:
    name: Running job2
    runs-on: ubuntu-latest
    steps:          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Remove faulty SDK version
        run: sudo rm -rf /usr/share/dotnet/sdk/7.0.4*
      - name: Get installed dotnet version
        run: dotnet --version