name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions in branch ${{ [github.ref_name] }}
on:
  workflow_dispatch:
    inputs:
      formula:
        description: 'Artifact Prefix'
        default: twilio
      branch:
        description: 'Branch name'
        default: main
jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.semantic-release.outputs.TAG_NAME }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Node install
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: |
          npm i
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#      - name: Display branch name and awk result
#        run: |
#          echo "Branch name is: ${{steps.extract_branch.outputs.branch}}"
#          echo $GITHUB_SHA
#          echo ${{ github.event.inputs.formula }}_$(awk -F- '{print $1}'
      - name: Run app file
        run: |
          node app.js
      - name: Trigger test workflow
        run: |
          fileName="$GITHUB_WORKSPACE/.github/scripts/trigger-workflow.js"
          node -e "require('$fileName').triggerWorkflow()"
        env:
          WORKFLOW_NAME: '.github/workflows/test.yml'
          REPO_NAME: ${{ github.repository_owner }}/TestGitHubActions
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          BRANCH_NAME: ${{steps.extract_branch.outputs.branch}}
      # - name: Semantic Release runs
      #   id: semantic-release
      #   run: DEBUG=semantic-release:* $(npm bin)/semantic-release  -t \${version}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      # - name: Print tag name
      #   run: |
      #     echo ${{ steps.semantic-release.outputs.TAG_NAME }}
      #     echo ${{ steps.semantic-release.outputs }}
      # - name: Verify rc branch
      #   if: contains(steps.semantic-release.outputs.TAG_NAME, 'rc' )
      #   run: echo "This is rc release"
      # - name: verify release required
      #   if: ${{steps.semantic-release.outputs.TAG_NAME == ''}}
      #   uses: actions/github-script@v3
      #   with:
      #     script: |
      #       core.setFailed('There are no relevant changes, so no new version is released.')
