name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List all files
        run: |
            ls
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: List all files after installation
        run: |
            npm install
            ls