name: Get Tag

on:
  workflow_dispatch

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get-latest-tag
        run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"

  your-other-job:
    runs-on: ubuntu-latest

    needs: get-latest-tag

    steps:
      - name: Use latest tag
        run: echo "Latest tag is ${{ needs.get-latest-tag.outputs.tag }}"
