name: Get Tag

on:
  workflow_dispatch

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Latest Tag
        run: echo "Latest tag is ${{ needs.get-latest-tag.outputs.tag }}"

