name: test-github-workflow
run-name: Branch name is ${{ inputs.branch }}
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Name'
        default: rc-branch
jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.semantic-release.outputs.TAG_NAME }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Node install
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: |
          npm i
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
