name: Update Manifest
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be tagged in release'
        required: true
        default: 1.0.5-rc.2

jobs:
  update-and-verify:
    name: Check Urls and Versions
    runs-on: windows-latest
    env:
      SCOOP: 'C:\Scoop\user'
    steps:
      - uses: actions/checkout@v2
      - name: Install Scoop
        run: |
          (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1') 
          ./scoop.ps1 -RunAsAdmin
          echo "$env:SCOOP\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Running ps1 commands
        run: |
          if(!$env:SCOOP_HOME) { $env:SCOOP_HOME = Resolve-Path (scoop prefix scoop) }
          $env:SCOOP_HOME
